function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // titmyname
	global.__objectDepths[1] = 0; // obtitsx
	global.__objectDepths[2] = 0; // obtitdx
	global.__objectDepths[3] = 0; // obtitmyname
	global.__objectDepths[4] = 0; // titrimpic
	global.__objectDepths[5] = 0; // obtitpreskey
	global.__objectDepths[6] = 0; // btn1vs1
	global.__objectDepths[7] = 0; // btn1vscpu
	global.__objectDepths[8] = 0; // btncommands
	global.__objectDepths[9] = 0; // btnlifex2
	global.__objectDepths[10] = -100; // oselsquare
	global.__objectDepths[11] = -100; // oselsq2
	global.__objectDepths[12] = 0; // oselgen
	global.__objectDepths[13] = 0; // osetberl
	global.__objectDepths[14] = 0; // osetbossi
	global.__objectDepths[15] = 0; // osetgaribaldi
	global.__objectDepths[16] = 0; // osetgaga
	global.__objectDepths[17] = 0; // osellarussa
	global.__objectDepths[18] = 0; // osellenin
	global.__objectDepths[19] = 0; // oseljakson
	global.__objectDepths[20] = 0; // oselozzy
	global.__objectDepths[21] = 0; // oselvendola
	global.__objectDepths[22] = 0; // oselrenato
	global.__objectDepths[23] = 0; // oselpapa
	global.__objectDepths[24] = 0; // oseljobs
	global.__objectDepths[25] = 0; // oselchristina
	global.__objectDepths[26] = 0; // oselheman
	global.__objectDepths[27] = 0; // oselobama
	global.__objectDepths[28] = 0; // oselgiorgiovanni
	global.__objectDepths[29] = 0; // oselcarra
	global.__objectDepths[30] = 0; // oselmrbrown
	global.__objectDepths[31] = 0; // oselbattiato
	global.__objectDepths[32] = 0; // oselfletcher
	global.__objectDepths[33] = 0; // oselmorte
	global.__objectDepths[34] = 0; // oselsatana
	global.__objectDepths[35] = 0; // oselnorris
	global.__objectDepths[36] = 0; // oselschettino
	global.__objectDepths[37] = 0; // oselemma
	global.__objectDepths[38] = 0; // oselbiber
	global.__objectDepths[39] = 0; // oselbastianich
	global.__objectDepths[40] = 0; // oselpadrino
	global.__objectDepths[41] = 0; // oselmike
	global.__objectDepths[42] = 0; // oselola
	global.__objectDepths[43] = 0; // oselbean
	global.__objectDepths[44] = 0; // oselsgarbi
	global.__objectDepths[45] = 0; // oselbanderas
	global.__objectDepths[46] = 0; // oselspierre
	global.__objectDepths[47] = 0; // oselpsy
	global.__objectDepths[48] = 0; // oselrandom
	global.__objectDepths[49] = 0; // stcolosseo
	global.__objectDepths[50] = 0; // stpisa
	global.__objectDepths[51] = 0; // stpriamar
	global.__objectDepths[52] = 0; // ststoneh
	global.__objectDepths[53] = 0; // stsvtorrette
	global.__objectDepths[54] = 0; // stsvplg
	global.__objectDepths[55] = 0; // sttour
	global.__objectDepths[56] = 0; // sttaj
	global.__objectDepths[57] = 0; // stcasabianca
	global.__objectDepths[58] = 0; // stbakingam
	global.__objectDepths[59] = 0; // stpiramidi
	global.__objectDepths[60] = 0; // stduomomilano
	global.__objectDepths[61] = 0; // stvaticano
	global.__objectDepths[62] = 0; // stgiappone
	global.__objectDepths[63] = -100; // msgbox
	global.__objectDepths[64] = -150; // mbtnok
	global.__objectDepths[65] = 0; // ocommands
	global.__objectDepths[66] = 0; // screenswitcher
	global.__objectDepths[67] = 0; // version_draw
	global.__objectDepths[68] = -500; // ohbarpl1
	global.__objectDepths[69] = -500; // ohbarpl2
	global.__objectDepths[70] = 0; // game_controller
	global.__objectDepths[71] = 0; // classplayer
	global.__objectDepths[72] = 0; // damage
	global.__objectDepths[73] = 1000; // opavimento
	global.__objectDepths[74] = 0; // owall
	global.__objectDepths[75] = 0; // pgbossi
	global.__objectDepths[76] = 0; // padanerasu
	global.__objectDepths[77] = -100; // bossifinal
	global.__objectDepths[78] = 0; // opadanon
	global.__objectDepths[79] = 0; // pggaga
	global.__objectDepths[80] = 0; // gaga_final
	global.__objectDepths[81] = 0; // gaga_monster
	global.__objectDepths[82] = 0; // pgozzy
	global.__objectDepths[83] = 0; // ometeor
	global.__objectDepths[84] = 0; // sozzy_final
	global.__objectDepths[85] = 0; // pgberl
	global.__objectDepths[86] = -100; // berleur
	global.__objectDepths[87] = -100; // berlmedia
	global.__objectDepths[88] = 0; // pglarussa
	global.__objectDepths[89] = -100; // larussafinal
	global.__objectDepths[90] = 0; // lrgranata
	global.__objectDepths[91] = 0; // explosion
	global.__objectDepths[92] = 0; // pgjakson
	global.__objectDepths[93] = -100; // vocalexplosion
	global.__objectDepths[94] = -100; // jakfinal
	global.__objectDepths[95] = 0; // pggaribaldi
	global.__objectDepths[96] = 0; // opallacannone
	global.__objectDepths[97] = 0; // ocom
	global.__objectDepths[98] = 0; // pglenin
	global.__objectDepths[99] = 0; // leninfinal
	global.__objectDepths[100] = -100; // laser
	global.__objectDepths[101] = 0; // pgvendola
	global.__objectDepths[102] = 0; // opalladisco
	global.__objectDepths[103] = -100; // vendolafinal
	global.__objectDepths[104] = 0; // pgrenato
	global.__objectDepths[105] = 0; // explosive0
	global.__objectDepths[106] = -100; // otriangolo2
	global.__objectDepths[107] = 0; // pgpapa
	global.__objectDepths[108] = 0; // granatasanta
	global.__objectDepths[109] = -100; // ocroce
	global.__objectDepths[110] = 0; // opapacap
	global.__objectDepths[111] = 0; // pgjobs
	global.__objectDepths[112] = -100; // oapple
	global.__objectDepths[113] = 0; // oiphone
	global.__objectDepths[114] = 0; // pgchristina_davena
	global.__objectDepths[115] = 0; // oheidi
	global.__objectDepths[116] = -100; // ogoingmerry
	global.__objectDepths[117] = 0; // pgobama
	global.__objectDepths[118] = -100; // obamafinal
	global.__objectDepths[119] = 0; // pgheman
	global.__objectDepths[120] = 0; // osword
	global.__objectDepths[121] = 0; // pgcarra
	global.__objectDepths[122] = 0; // explosivecarra
	global.__objectDepths[123] = 0; // olottoball
	global.__objectDepths[124] = 0; // pgmrbrown
	global.__objectDepths[125] = -100; // onyancat
	global.__objectDepths[126] = 0; // obandierainglese
	global.__objectDepths[127] = -100; // orainbow
	global.__objectDepths[128] = 0; // pgbattiato
	global.__objectDepths[129] = -100; // ochibakutensei
	global.__objectDepths[130] = 0; // oshinratensei
	global.__objectDepths[131] = 0; // pgfletcher
	global.__objectDepths[132] = 0; // ogattonero
	global.__objectDepths[133] = -100; // oincudine
	global.__objectDepths[134] = 0; // pgmorte
	global.__objectDepths[135] = -100; // oteschio
	global.__objectDepths[136] = -100; // obara
	global.__objectDepths[137] = 0; // pgsatana
	global.__objectDepths[138] = -100; // osatanaseal
	global.__objectDepths[139] = -100; // o666
	global.__objectDepths[140] = 1000; // pgnorris
	global.__objectDepths[141] = -100; // oflypunch
	global.__objectDepths[142] = 0; // obazoka
	global.__objectDepths[143] = -100; // omnuc
	global.__objectDepths[144] = 0; // pgskettino
	global.__objectDepths[145] = -100; // ocrociera
	global.__objectDepths[146] = -100; // odragon
	global.__objectDepths[147] = 0; // ocappellocapitano
	global.__objectDepths[148] = 0; // pgemma
	global.__objectDepths[149] = -100; // ocuore
	global.__objectDepths[150] = 0; // onota
	global.__objectDepths[151] = 0; // pgbastianich
	global.__objectDepths[152] = -100; // ovomit
	global.__objectDepths[153] = 0; // opiatto
	global.__objectDepths[154] = 0; // pgpadrino
	global.__objectDepths[155] = -100; // opadr
	global.__objectDepths[156] = 0; // oproiettile
	global.__objectDepths[157] = -100; // othompson
	global.__objectDepths[158] = 0; // pgmike
	global.__objectDepths[159] = -100; // oruota
	global.__objectDepths[160] = 0; // pgola
	global.__objectDepths[161] = -100; // otesta_ola
	global.__objectDepths[162] = -100; // odisco
	global.__objectDepths[163] = 0; // gencapre
	global.__objectDepths[164] = 0; // pgsgarbi
	global.__objectDepths[165] = 0; // ocapra
	global.__objectDepths[166] = -100; // omonalisa
	global.__objectDepths[167] = 0; // pgspierre
	global.__objectDepths[168] = 0; // pgvanni
	global.__objectDepths[169] = 0; // opokeball
	global.__objectDepths[170] = 0; // okyuby
	global.__objectDepths[171] = -100; // obijudama
	global.__objectDepths[172] = 0; // ovexpl
	global.__objectDepths[173] = 0; // object171


	global.__objectNames[0] = "titmyname";
	global.__objectNames[1] = "obtitsx";
	global.__objectNames[2] = "obtitdx";
	global.__objectNames[3] = "obtitmyname";
	global.__objectNames[4] = "titrimpic";
	global.__objectNames[5] = "obtitpreskey";
	global.__objectNames[6] = "btn1vs1";
	global.__objectNames[7] = "btn1vscpu";
	global.__objectNames[8] = "btncommands";
	global.__objectNames[9] = "btnlifex2";
	global.__objectNames[10] = "oselsquare";
	global.__objectNames[11] = "oselsq2";
	global.__objectNames[12] = "oselgen";
	global.__objectNames[13] = "osetberl";
	global.__objectNames[14] = "osetbossi";
	global.__objectNames[15] = "osetgaribaldi";
	global.__objectNames[16] = "osetgaga";
	global.__objectNames[17] = "osellarussa";
	global.__objectNames[18] = "osellenin";
	global.__objectNames[19] = "oseljakson";
	global.__objectNames[20] = "oselozzy";
	global.__objectNames[21] = "oselvendola";
	global.__objectNames[22] = "oselrenato";
	global.__objectNames[23] = "oselpapa";
	global.__objectNames[24] = "oseljobs";
	global.__objectNames[25] = "oselchristina";
	global.__objectNames[26] = "oselheman";
	global.__objectNames[27] = "oselobama";
	global.__objectNames[28] = "oselgiorgiovanni";
	global.__objectNames[29] = "oselcarra";
	global.__objectNames[30] = "oselmrbrown";
	global.__objectNames[31] = "oselbattiato";
	global.__objectNames[32] = "oselfletcher";
	global.__objectNames[33] = "oselmorte";
	global.__objectNames[34] = "oselsatana";
	global.__objectNames[35] = "oselnorris";
	global.__objectNames[36] = "oselschettino";
	global.__objectNames[37] = "oselemma";
	global.__objectNames[38] = "oselbiber";
	global.__objectNames[39] = "oselbastianich";
	global.__objectNames[40] = "oselpadrino";
	global.__objectNames[41] = "oselmike";
	global.__objectNames[42] = "oselola";
	global.__objectNames[43] = "oselbean";
	global.__objectNames[44] = "oselsgarbi";
	global.__objectNames[45] = "oselbanderas";
	global.__objectNames[46] = "oselspierre";
	global.__objectNames[47] = "oselpsy";
	global.__objectNames[48] = "oselrandom";
	global.__objectNames[49] = "stcolosseo";
	global.__objectNames[50] = "stpisa";
	global.__objectNames[51] = "stpriamar";
	global.__objectNames[52] = "ststoneh";
	global.__objectNames[53] = "stsvtorrette";
	global.__objectNames[54] = "stsvplg";
	global.__objectNames[55] = "sttour";
	global.__objectNames[56] = "sttaj";
	global.__objectNames[57] = "stcasabianca";
	global.__objectNames[58] = "stbakingam";
	global.__objectNames[59] = "stpiramidi";
	global.__objectNames[60] = "stduomomilano";
	global.__objectNames[61] = "stvaticano";
	global.__objectNames[62] = "stgiappone";
	global.__objectNames[63] = "msgbox";
	global.__objectNames[64] = "mbtnok";
	global.__objectNames[65] = "ocommands";
	global.__objectNames[66] = "screenswitcher";
	global.__objectNames[67] = "version_draw";
	global.__objectNames[68] = "ohbarpl1";
	global.__objectNames[69] = "ohbarpl2";
	global.__objectNames[70] = "game_controller";
	global.__objectNames[71] = "classplayer";
	global.__objectNames[72] = "damage";
	global.__objectNames[73] = "opavimento";
	global.__objectNames[74] = "owall";
	global.__objectNames[75] = "pgbossi";
	global.__objectNames[76] = "padanerasu";
	global.__objectNames[77] = "bossifinal";
	global.__objectNames[78] = "opadanon";
	global.__objectNames[79] = "pggaga";
	global.__objectNames[80] = "gaga_final";
	global.__objectNames[81] = "gaga_monster";
	global.__objectNames[82] = "pgozzy";
	global.__objectNames[83] = "ometeor";
	global.__objectNames[84] = "sozzy_final";
	global.__objectNames[85] = "pgberl";
	global.__objectNames[86] = "berleur";
	global.__objectNames[87] = "berlmedia";
	global.__objectNames[88] = "pglarussa";
	global.__objectNames[89] = "larussafinal";
	global.__objectNames[90] = "lrgranata";
	global.__objectNames[91] = "explosion";
	global.__objectNames[92] = "pgjakson";
	global.__objectNames[93] = "vocalexplosion";
	global.__objectNames[94] = "jakfinal";
	global.__objectNames[95] = "pggaribaldi";
	global.__objectNames[96] = "opallacannone";
	global.__objectNames[97] = "ocom";
	global.__objectNames[98] = "pglenin";
	global.__objectNames[99] = "leninfinal";
	global.__objectNames[100] = "laser";
	global.__objectNames[101] = "pgvendola";
	global.__objectNames[102] = "opalladisco";
	global.__objectNames[103] = "vendolafinal";
	global.__objectNames[104] = "pgrenato";
	global.__objectNames[105] = "explosive0";
	global.__objectNames[106] = "otriangolo2";
	global.__objectNames[107] = "pgpapa";
	global.__objectNames[108] = "granatasanta";
	global.__objectNames[109] = "ocroce";
	global.__objectNames[110] = "opapacap";
	global.__objectNames[111] = "pgjobs";
	global.__objectNames[112] = "oapple";
	global.__objectNames[113] = "oiphone";
	global.__objectNames[114] = "pgchristina_davena";
	global.__objectNames[115] = "oheidi";
	global.__objectNames[116] = "ogoingmerry";
	global.__objectNames[117] = "pgobama";
	global.__objectNames[118] = "obamafinal";
	global.__objectNames[119] = "pgheman";
	global.__objectNames[120] = "osword";
	global.__objectNames[121] = "pgcarra";
	global.__objectNames[122] = "explosivecarra";
	global.__objectNames[123] = "olottoball";
	global.__objectNames[124] = "pgmrbrown";
	global.__objectNames[125] = "onyancat";
	global.__objectNames[126] = "obandierainglese";
	global.__objectNames[127] = "orainbow";
	global.__objectNames[128] = "pgbattiato";
	global.__objectNames[129] = "ochibakutensei";
	global.__objectNames[130] = "oshinratensei";
	global.__objectNames[131] = "pgfletcher";
	global.__objectNames[132] = "ogattonero";
	global.__objectNames[133] = "oincudine";
	global.__objectNames[134] = "pgmorte";
	global.__objectNames[135] = "oteschio";
	global.__objectNames[136] = "obara";
	global.__objectNames[137] = "pgsatana";
	global.__objectNames[138] = "osatanaseal";
	global.__objectNames[139] = "o666";
	global.__objectNames[140] = "pgnorris";
	global.__objectNames[141] = "oflypunch";
	global.__objectNames[142] = "obazoka";
	global.__objectNames[143] = "omnuc";
	global.__objectNames[144] = "pgskettino";
	global.__objectNames[145] = "ocrociera";
	global.__objectNames[146] = "odragon";
	global.__objectNames[147] = "ocappellocapitano";
	global.__objectNames[148] = "pgemma";
	global.__objectNames[149] = "ocuore";
	global.__objectNames[150] = "onota";
	global.__objectNames[151] = "pgbastianich";
	global.__objectNames[152] = "ovomit";
	global.__objectNames[153] = "opiatto";
	global.__objectNames[154] = "pgpadrino";
	global.__objectNames[155] = "opadr";
	global.__objectNames[156] = "oproiettile";
	global.__objectNames[157] = "othompson";
	global.__objectNames[158] = "pgmike";
	global.__objectNames[159] = "oruota";
	global.__objectNames[160] = "pgola";
	global.__objectNames[161] = "otesta_ola";
	global.__objectNames[162] = "odisco";
	global.__objectNames[163] = "gencapre";
	global.__objectNames[164] = "pgsgarbi";
	global.__objectNames[165] = "ocapra";
	global.__objectNames[166] = "omonalisa";
	global.__objectNames[167] = "pgspierre";
	global.__objectNames[168] = "pgvanni";
	global.__objectNames[169] = "opokeball";
	global.__objectNames[170] = "okyuby";
	global.__objectNames[171] = "obijudama";
	global.__objectNames[172] = "ovexpl";
	global.__objectNames[173] = "object171";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
